# Configuration for the CODA dashboard
# This file defines the repositories to fetch issues from

repositories:
  - owner: canonical
    repo: ulwazi
    labels:
      - documentation
      - bug
    maintainer(s):
      name: Vladimir Izmalkov
      github: izmalk
    contributor guide: https://documentation.ubuntu.com/ulwazi/content/contribute/

  - owner: canonical
    repo: microceph
    labels:
      - coda
    maintainer(s):
      name: Sharon Koech
      github: skoech
    contributor guide: https://documentation.ubuntu.com/microceph/stable/contributing/

  - owner: canonical
    repo: open-documentation-academy
    labels:
      - coda
    maintainer(s):
      - name: Graham Morrison
        github: degville
      - name: Sophie Pages
        github: sophiepages
      - name: Sharon Koech
        github: skoech
    contributor guide: 

  - owner: canonical
    repo: chisel-docs
    labels:
      - edit
    maintainer(s):
      name: Anna Sancho Vaquer
      github: asanvag
    contributor guide: 

  - owner: canonical
    repo: rockcraft
    labels:
      - edit
    maintainer(s):
      name: Anna Sancho Vaquer
      github: asanvag
    contributor guide: